/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;


public class PopulationCounterTest {

    @Test
    public void max() throws Exception{
        assertEquals(2, 2);
    }

    
    // @Test
    // public void testSomeLibraryMethod() throws Exception {
    //     ReadFileCSV readfile = new ReadFileCSV("./data/worldcitiespop.csv");
    //     ParsingCSVData data = new ParsingCSVData(readfile.getFileData());
    //     CalculateSum s = new CalculateSum(data.getPopText());
    //     assertEquals(1347982728, s.getTotalPop());
    // }


    // @Test
    // public void testingFileRead() throws Exception{
    //     ReadFileCSV rr = new ReadFileCSV("./data/worldcitiespop.csv");
    //     assertEquals("Country,City,AccentCity,Region,Population,Latitude,Longitude", rr.getFileData().get(0));
    // }

    
}
