/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.jupiter.api.Test;

import static org.mockito.Mockito.mock;

public class PopulationCounterTest {
    @Test
    public void testSomeLibraryMethod() throws Exception {

        // Setup
        String expected = "World population is: 1,347,982,728";

        // https://stackoverflow.com/questions/8708342/redirect-console-output-to-string-in-java
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(baos);
        PrintStream old = System.out;
        System.setOut(ps);

        // Exercise
        // PopulationCounter.main(new String[] {"./data/worldcitiespop.csv"});

        ReadFileCSV readfile = new ReadFileCSV("./data/worldcitiespop.csv");
        ParsingCSVData data = new ParsingCSVData(readfile.getFileData());
        CalculateSum s = new CalculateSum(data.getPopText());

        // Assert
        System.out.flush();
        String output = baos.toString();
        assertEquals(1347982728, s.getTotalPop());

        // Teardown
        System.setOut(old);
    }


    @Test
    public void TestingFileRea(){

        ReadFileCSV rr = new ReadFileCSV("./data/worldcitiespop.csv");
        
        
        

    }
}
